# Generated by Django 3.1 on 2020-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalIdCard', models.ImageField(upload_to='docs/nid')),
                ('ownershipCertificate', models.ImageField(upload_to='docs/oc')),
                ('cadatralMap', models.ImageField(upload_to='docs/cm')),
                ('capacityCalculation', models.ImageField(upload_to='docs/cc')),
            ],
        ),
        migrations.CreateModel(
            name='CapacityCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FieldInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groundInformationSector', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('landTitleNumber', models.IntegerField(null=True)),
                ('requisitionNumber', models.IntegerField(null=True)),
                ('calledProperty', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RequesterInformationNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalIdCard', models.CharField(max_length=50, null=True, unique=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('role', models.CharField(max_length=1)),
                ('email', models.CharField(blank=True, max_length=60, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInformationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInformationNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1)),
                ('sendingDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInformationVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
