# Generated by Django 3.1 on 2020-09-30 18:01

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nationalIdCard', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttachedDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RequestInformationNote', models.FileField(null=True, upload_to='docs/rin')),
                ('ownershipCertificate', models.FileField(upload_to='docs/oc')),
                ('cadatralMap', models.FileField(upload_to='docs/cm')),
                ('nationalIdCard', models.FileField(upload_to='docs/nid')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('agencyStaff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.agencystaff')),
            ],
        ),
        migrations.CreateModel(
            name='FieldInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groundInformationSector', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('landTitleNumber', models.IntegerField(null=True)),
                ('requisitionNumber', models.IntegerField(null=True)),
                ('calledProperty', models.CharField(max_length=50, null=True)),
                ('capacityCalculation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), size=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequesterInformationNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nationalIdCard', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInformationVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requesterInformation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.requesterinformationnote')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInformationNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='p', max_length=1)),
                ('sendingDate', models.DateField(auto_now_add=True, null=True)),
                ('requesterInformationNote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.requesterinformationnote')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(null=True, upload_to='pub/files'), null=True, size=10)),
                ('agencyStaff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.agencystaff')),
                ('comments', models.ManyToManyField(to='API.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInformationContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attachedDocument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.attacheddocument')),
                ('fieldInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.fieldinformation')),
                ('requestInformationNote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.requestinformationnote')),
            ],
            options={
                'unique_together': {('requestInformationNote', 'fieldInformation', 'attachedDocument')},
                'index_together': {('requestInformationNote', 'fieldInformation', 'attachedDocument')},
            },
        ),
    ]
