# Generated by Django 3.1 on 2020-10-25 12:42

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nationalIdCard', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('agencyStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.agencystaff')),
            ],
        ),
        migrations.CreateModel(
            name='RequesterInformationNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nationalIdCard', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=250, null=True)),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInformationNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='p', max_length=1)),
                ('rejection_message', models.CharField(max_length=200, null=True)),
                ('sendingDate', models.DateTimeField(auto_now=True)),
                ('groundInformationSector', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('landTitleNumber', models.IntegerField(null=True)),
                ('requisitionNumber', models.IntegerField(null=True)),
                ('calledProperty', models.CharField(max_length=50, null=True)),
                ('capacityCalculation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), size=10)),
                ('requestInformationNote', models.FileField(upload_to='docs/rin')),
                ('ownershipCertificate', models.FileField(upload_to='docs/oc')),
                ('cadatralMap', models.FileField(upload_to='docs/cm')),
                ('nationalIdCard', models.FileField(upload_to='docs/nid')),
                ('requesterInformationNote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.requesterinformationnote')),
            ],
        ),
        migrations.CreateModel(
            name='RequestInformationVerification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agencyStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.agencystaff')),
                ('requestInformationNote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.requestinformationnote')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='pub/')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='API.publication')),
            ],
        ),
        migrations.CreateModel(
            name='InformationNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='information_note')),
                ('agencyStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.agencystaff')),
                ('noteInformationRequester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.requesterinformationnote')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=100)),
                ('agencyStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.agencystaff')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='API.publication')),
            ],
        ),
    ]
