# Generated by Django 3.1 on 2020-08-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitycalculation',
            name='reference',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
