# Generated by Django 3.1 on 2020-10-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationnote',
            old_name='document',
            new_name='information_note_document',
        ),
        migrations.RenameField(
            model_name='informationnote',
            old_name='date',
            new_name='saving_date',
        ),
        migrations.RenameField(
            model_name='requestinformationverification',
            old_name='date',
            new_name='verification_date',
        ),
        migrations.RemoveField(
            model_name='requestinformationnote',
            name='rejection_message',
        ),
        migrations.RemoveField(
            model_name='requestinformationnote',
            name='state',
        ),
        migrations.AddField(
            model_name='requestinformationverification',
            name='rejection_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestinformationverification',
            name='request_state',
            field=models.CharField(default='p', max_length=1),
        ),
    ]
