# Generated by Django 3.1 on 2020-09-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinformationnote',
            name='sendingDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
