# Generated by Django 3.1 on 2020-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201007_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedfile',
            name='filePath',
            field=models.FileField(default='default', upload_to='pub/'),
            preserve_default=False,
        ),
    ]
