# Generated by Django 3.1 on 2020-08-16 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_capacitycalculation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitycalculation',
            name='xCoordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='capacitycalculation',
            name='yCoordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
