# Generated by Django 3.1 on 2020-10-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201030_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinformationverification',
            name='agencyStaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.agencystaff'),
        ),
    ]
