# Generated by Django 3.1 on 2020-09-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200930_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinformationnote',
            name='sendingDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='requestinformationnote',
            name='state',
            field=models.CharField(default='progress', max_length=10),
        ),
    ]
