# Generated by Django 3.1 on 2020-10-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200930_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacheddocument',
            old_name='RequestInformationNote',
            new_name='requestInformationNote',
        ),
    ]
