# Generated by Django 3.1 on 2020-10-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_publishedfile_filepath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishedfile',
            old_name='filePath',
            new_name='file',
        ),
    ]
