# Generated by Django 3.1 on 2020-08-16 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200816_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitycalculation',
            name='bounds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), null=True, size=None),
        ),
    ]
