# Generated by Django 3.1 on 2020-10-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20201030_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinformationverification',
            name='verification_date',
            field=models.DateTimeField(null=True),
        ),
    ]
