# Generated by Django 3.1 on 2020-10-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201030_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationnote',
            old_name='information_note_document',
            new_name='document',
        ),
    ]
