# Generated by Django 3.1 on 2020-08-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_capacitycalculation_bounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='agencyStaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.agencystaff'),
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(null=True, upload_to='pub/files'),
        ),
        migrations.AddField(
            model_name='requestinformationnote',
            name='requesterInformationNote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.requesterinformationnote'),
        ),
    ]
