# Generated by Django 3.1 on 2020-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201001_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencystaff',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agencystaff',
            name='phoneNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
