# Generated by Django 3.1 on 2020-10-11 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0005_auto_20201011_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencystaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='requesterinformationnote',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='requestinformationnote',
            name='requestInformationNote',
            field=models.FileField(upload_to='docs/rin'),
        ),
        migrations.AlterField(
            model_name='requestinformationnote',
            name='requesterInformationNote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.requesterinformationnote'),
        ),
    ]
