# Generated by Django 3.1 on 2020-10-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201030_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestinformationverification',
            old_name='verification_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='requestinformationverification',
            old_name='request_state',
            new_name='state',
        ),
    ]
