# Generated by Django 3.1 on 2020-08-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200816_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencystaff',
            name='role',
            field=models.CharField(choices=[('NIR', 'noteInformationRequester'), ('AS', 'agencyStaff')], max_length=3),
        ),
        migrations.AlterField(
            model_name='requesterinformationnote',
            name='email',
            field=models.EmailField(blank=True, max_length=60, unique=True),
        ),
    ]
