# Generated by Django 3.1 on 2020-08-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200816_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencystaff',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='requesterinformationnote',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
