# Generated by Django 3.1 on 2020-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20201016_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinformationverification',
            name='capacityAdopted_correspondence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestinformationverification',
            name='capacityCalculation_validity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestinformationverification',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requestinformationverification',
            name='landTitleNumber_correspondence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestinformationverification',
            name='noteRequester_correspondence',
            field=models.BooleanField(default=False),
        ),
    ]
