# Generated by Django 3.1 on 2020-10-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20201018_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinformationverification',
            name='rejection_message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
