# Generated by Django 3.1 on 2020-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20201018_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinformationnote',
            name='state',
            field=models.CharField(default='p', max_length=1),
        ),
    ]
