# Generated by Django 3.1 on 2020-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20201020_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinformationnote',
            name='state',
            field=models.CharField(default='p', max_length=10),
        ),
    ]
